export RUST_BACKTRACE := "1"

openocd:
    openocd -f interface/stlink.cfg -f target/stm32g4x.cfg

clean:
    cargo clean

check CRATE:
    cargo check -p {{ CRATE }}

run CRATE:
    cargo run --bin {{ CRATE }}

build CRATE:
    cargo build --bin {{ CRATE }}

attach TARGET:
    probe-rs attach --chip STM32H753ZITx ./target/thumbv7em-none-eabihf/debug/{{ TARGET }}
