[package]
name = "day_1"
version = "0.1.0"
edition = "2024"

[dependencies]
divan = "0.1.17"
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "divan_bench"
# name = "criterion_bench"
harness = false

